name: habit_tracker
description: "Habit tracker that helps to monitor activity"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.1
  firebase_core: ^3.4.0
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  easy_localization: ^3.0.7
  shared_preferences: ^2.3.2
  drift: ^2.19.1+1
  drift_flutter: ^0.2.0
  flutter_gen: ^5.7.0
  flutter_svg: ^2.0.10+1
  flutter_animate: ^4.5.0
  get_it: ^7.7.0
  injectable: ^2.4.4
  provider: ^6.1.2
  password_strength_checker: ^1.2.4
  path_provider: ^2.1.4
  intl: ^0.19.0
  flutter_slidable: ^3.1.1
  flutter_in_app_color_filter:
    path: ../flutter_in_app_color_filter

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.19.1
  build_runner: ^2.4.12
  flutter_gen_runner: ^5.7.0
  injectable_generator: ^2.6.2
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1


flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/png/app_icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - assets/translations/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
          style: normal
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
          style: normal
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
          style: normal
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
          style: normal


flutter_native_splash:
  color: "#7E49FF"

flutter_gen:
  output: lib/gen/
  line_length: 120
  integrations:
    flutter_svg: true
    lottie: true
  assets:
    enabled: true
    fonts:
      enabled: false
    output:
      style: dot-delimiter
      package_parameter_enabled: true
      synthetic-package: false